name: MacOS Build


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  MacOS:
    env:
      # app archive 및 export 에 쓰일 환경 변수 설정
      XC_WORKSPACE: ${{ 'platforms/iOS/CSEngine.xcodeproj' }}
      XC_SCHEME: ${{ 'CSEngine' }}
      XC_ARCHIVE: ${{ 'CSEngine.xcarchive' }}
    strategy:
      matrix:
          macos-version: [ macos-latest ]
          compiler: [ clang ]
          include:
            - compiler: clang
              compiler-CXX: clang++
              
    runs-on: ${{ matrix.macos-version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'ounols/CSEngine'
          
      - name: Select latest Xcode
        # shell 이용해서 하나의 command 수행
        run: "sudo xcode-select -s /Applications/Xcode.app"
        
      - name: Archive app
        # 빌드 및 아카이브
        run: |
          xcodebuild clean build -project $XC_WORKSPACE -scheme $XC_SCHEME -allowProvisioningUpdates

      
